/* eslint-disable @typescript-eslint/no-explicit-any */
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { AlertTriangle, BadgeCheck, Banknote, Clock, Search, Wallet } from "lucide-react";
import { PageHeader } from "@/components/layout/AppShell";
import { DataTable } from "@/components/CrudModule";
import { StatCard } from "@/components/StatCard";
import { StatusBadge } from "@/components/StatusBadge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useCurrentUser } from "@/hooks/useAuth";
import { db, type Row } from "@/lib/db";
import { logAudit } from "@/lib/audit";
import { formatDate, formatDateTime, formatNaira, titleCase } from "@/lib/format";

export const Route = createFileRoute("/_authenticated/commissions")({
  head: () => ({
    meta: [
      { title: "Commission Control Centre — NEOMARC NDOS" },
      {
        name: "description",
        content:
          "Track, approve and pay realtor commissions generated by the NEOMARC commission engine.",
      },
      { property: "og:title", content: "Commission Control Centre — NEOMARC NDOS" },
      {
        property: "og:description",
        content:
          "Pending, approved, payable and paid realtor commissions with live liability totals.",
      },
    ],
  }),
  component: CommissionsPage,
});

const NEXT: Record<string, { to: string; label: string }[]> = {
  pending: [
    { to: "approved", label: "Approve" },
    { to: "cancelled", label: "Cancel" },
  ],
  approved: [
    { to: "payable", label: "Mark payable" },
    { to: "cancelled", label: "Cancel" },
  ],
  payable: [{ to: "paid", label: "Mark paid" }],
};

const SELECT = `
  id, ref, status, rate, amount, amount_paid, sale_value, fixed_component, notes,
  created_at, approved_at, payable_at, paid_at, reversed_at, is_auto, rule_id,
  realtors:realtor_id ( full_name ),
  customers:customer_id ( full_name ),
  estates:estate_id ( name ),
  properties:property_id ( plot_number, block ),
  sales:sale_id ( id, ref, sales_channel ),
  commission_rules:rule_id ( name, rate )
`;

function CommissionsPage() {
  const qc = useQueryClient();
  const { data: me } = useCurrentUser();
  const canManage = !!me && (me.isAdmin || me.roles.includes("accounts"));
  const [term, setTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [confirm, setConfirm] = useState<{ row: Row; to: string; label: string } | null>(null);

  const { data: rows = [], isLoading } = useQuery({
    queryKey: ["commissions", "control-centre"],
    queryFn: async () => {
      const { data, error } = await db
        .from("commissions")
        .select(SELECT)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return (data ?? []) as Row[];
    },
  });

  // "COMMISSION RULE MISSING" — raised by the database when no active rule applied,
  // which is a different state from a valid rule that computed ₦0.
  const { data: issues = [] } = useQuery({
    queryKey: ["commission_accrual_issues", "open"],
    queryFn: async () => {
      const { data } = await db
        .from("commission_accrual_issues")
        .select(
          "id, reason, detail, referral_type, created_at, sales:sale_id ( ref ), realtors:realtor_id ( full_name ), estates:estate_id ( name )",
        )
        .is("resolved_at", null)
        .order("created_at", { ascending: false });
      return (data ?? []) as Row[];
    },
  });


  const transition = useMutation({
    mutationFn: async ({ row, to }: { row: Row; to: string }) => {
      const { error } = await db.from("commissions").update({ status: to }).eq("id", row.id);
      if (error) throw error;
      await logAudit({
        action: `commission_${to}`,
        table: "commissions",
        recordId: row.id,
        previous: { status: row.status },
        next: { status: to },
      });
    },
    onSuccess: () => {
      toast.success("Commission status updated");
      setConfirm(null);
      qc.invalidateQueries();
    },
    onError: (e: any) => toast.error(e.message ?? "Not permitted"),
  });

  const filtered = useMemo(() => {
    const t = term.trim().toLowerCase();
    return rows.filter((r) => {
      if (statusFilter !== "all" && r.status !== statusFilter) return false;
      if (!t) return true;
      return [
        r.ref,
        r.sales?.ref,
        r.realtors?.full_name,
        r.customers?.full_name,
        r.estates?.name,
      ].some((v) =>
        String(v ?? "")
          .toLowerCase()
          .includes(t),
      );
    });
  }, [rows, term, statusFilter]);

  const sum = (status: string) =>
    rows.filter((r) => r.status === status).reduce((a, r) => a + Number(r.amount ?? 0), 0);
  const liability = rows
    .filter((r) => ["pending", "approved", "payable"].includes(r.status))
    .reduce((a, r) => a + Number(r.amount ?? 0) - Number(r.amount_paid ?? 0), 0);
  const zeroRows = rows.filter((r) => Number(r.amount ?? 0) <= 0 && r.status !== "reversed");

  return (
    <div className="space-y-6">
      <PageHeader
        title="Commission Control Centre"
        description="Every figure is generated by the database commission engine — nothing is recalculated here."
      />

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        <StatCard
          label="Pending"
          value={formatNaira(sum("pending"), true)}
          icon={Clock}
          tone="warning"
        />
        <StatCard
          label="Approved"
          value={formatNaira(sum("approved"), true)}
          icon={BadgeCheck}
          tone="info"
        />
        <StatCard
          label="Payable"
          value={formatNaira(sum("payable"), true)}
          icon={Wallet}
          tone="gold"
        />
        <StatCard
          label="Paid"
          value={formatNaira(sum("paid"), true)}
          icon={Banknote}
          tone="success"
        />
        <StatCard
          label="Total liability"
          value={formatNaira(liability, true)}
          hint="Unpaid, non-reversed commissions"
          icon={AlertTriangle}
          tone="destructive"
        />
      </div>

      {issues.length ? (
        <div className="surface-card space-y-2 border-destructive/50 p-4 text-sm">
          <p className="flex items-center gap-2 font-medium text-destructive">
            <AlertTriangle className="h-4 w-4" /> Commission rule missing
          </p>
          <p className="text-xs text-muted-foreground">
            No commission was accrued for these sales because no active rule applied. An
            administrator must configure a rule — nothing is paid on a fallback rate.
          </p>
          {issues.map((i) => (
            <p key={i.id} className="text-muted-foreground">
              Sale {i.sales?.ref ?? "—"} · {titleCase(i.referral_type ?? "direct")} ·{" "}
              {i.realtors?.full_name ?? "realtor"} · {i.estates?.name ?? "no estate"} —{" "}
              {i.reason === "rule_missing" ? "COMMISSION RULE MISSING" : titleCase(i.reason ?? "")}
            </p>
          ))}
        </div>
      ) : null}

      {zeroRows.length ? (
        <div className="surface-card space-y-2 border-warning/40 p-4 text-sm">
          <p className="flex items-center gap-2 font-medium">
            <AlertTriangle className="h-4 w-4 text-warning-foreground" /> ₦0 commissions
          </p>
          <p className="text-xs text-muted-foreground">
            A valid rule applied but the calculated commission is zero — distinct from a missing
            rule.
          </p>
          {zeroRows.map((r) => (
            <p key={r.id} className="text-muted-foreground">
              {r.ref} — ₦0 at {Number(r.rate ?? 0)}%
              {r.commission_rules?.name ? ` (rule: ${r.commission_rules.name})` : ""}
            </p>
          ))}
        </div>
      ) : null}


      <div className="flex flex-wrap items-center gap-2">
        <div className="relative min-w-[200px] flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            className="pl-9"
            placeholder="Search ref, sale, realtor, customer…"
            value={term}
            onChange={(e) => setTerm(e.target.value)}
          />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-[180px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {["all", "pending", "approved", "payable", "paid", "cancelled", "reversed"].map((s) => (
              <SelectItem key={s} value={s}>
                {s === "all" ? "All statuses" : titleCase(s)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <DataTable
        columns={[
          {
            key: "ref",
            label: "Commission",
            render: (r) => (
              <div className="min-w-[150px]">
                <p className="font-medium">{r.ref}</p>
                <p className="text-xs text-muted-foreground">
                  {r.sales?.ref ? (
                    <Link
                      to="/sales/$saleId"
                      params={{ saleId: r.sales.id }}
                      className="hover:underline"
                    >
                      Sale {r.sales.ref}
                    </Link>
                  ) : (
                    "No sale"
                  )}
                </p>
              </div>
            ),
          },
          {
            key: "estate",
            label: "Estate / Plot",
            render: (r) => (
              <div className="min-w-[140px]">
                <p>{r.estates?.name ?? "—"}</p>
                <p className="text-xs text-muted-foreground">
                  {[r.properties?.block, r.properties?.plot_number].filter(Boolean).join(" / ") ||
                    "—"}
                </p>
              </div>
            ),
          },
          {
            key: "parties",
            label: "Realtor / Customer",
            render: (r) => (
              <div className="min-w-[140px]">
                <p>{r.realtors?.full_name ?? "—"}</p>
                <p className="text-xs text-muted-foreground">{r.customers?.full_name ?? "—"}</p>
              </div>
            ),
          },
          {
            key: "channel",
            label: "Referral type",
            render: (r) => (
              <div className="min-w-[110px]">
                <p>{titleCase(r.referral_type ?? "direct")}</p>
                <p className="text-xs text-muted-foreground">
                  {titleCase(r.sales?.sales_channel ?? "direct")} channel
                </p>
              </div>
            ),
          },

          { key: "rate", label: "Rate", render: (r) => `${Number(r.rate ?? 0)}%` },
          {
            key: "amount",
            label: "Amount",
            render: (r) => (
              <span className={Number(r.amount ?? 0) <= 0 ? "text-destructive" : undefined}>
                {formatNaira(r.amount)}
              </span>
            ),
          },
          { key: "amount_paid", label: "Paid", render: (r) => formatNaira(r.amount_paid) },
          {
            key: "rule",
            label: "Rule / source",
            render: (r) => (
              <span className="text-xs text-muted-foreground">
                {r.commission_rules?.name ?? (r.is_auto ? "Realtor default rate" : "Manual entry")}
              </span>
            ),
          },
          { key: "status", label: "Status", render: (r) => <StatusBadge value={r.status} /> },
          {
            key: "dates",
            label: "Lifecycle",
            render: (r) => (
              <div className="min-w-[150px] text-xs text-muted-foreground">
                <p>Created {formatDate(r.created_at)}</p>
                {r.approved_at ? <p>Approved {formatDateTime(r.approved_at)}</p> : null}
                {r.payable_at ? <p>Payable {formatDateTime(r.payable_at)}</p> : null}
                {r.paid_at ? <p>Paid {formatDateTime(r.paid_at)}</p> : null}
                {r.reversed_at ? <p>Reversed {formatDateTime(r.reversed_at)}</p> : null}
              </div>
            ),
          },
        ]}
        rows={filtered}
        loading={isLoading}
        empty="No commissions accrued yet."
        actions={
          canManage
            ? (row) => (
                <div className="flex flex-wrap justify-end gap-1">
                  {(NEXT[row.status] ?? []).map((a) => (
                    <Button
                      key={a.to}
                      size="sm"
                      variant={a.to === "cancelled" ? "ghost" : "outline"}
                      onClick={() => setConfirm({ row, to: a.to, label: a.label })}
                    >
                      {a.label}
                    </Button>
                  ))}
                </div>
              )
            : undefined
        }
      />

      <AlertDialog open={!!confirm} onOpenChange={(v) => !v && setConfirm(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              {confirm?.label} commission {confirm?.row.ref}?
            </AlertDialogTitle>
            <AlertDialogDescription>
              {confirm ? formatNaira(confirm.row.amount) : ""} for{" "}
              {confirm?.row.realtors?.full_name ?? "this realtor"}. The database records the actor
              and timestamp; the change is rejected if your role is not authorised.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => confirm && transition.mutate({ row: confirm.row, to: confirm.to })}
            >
              Confirm
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
