/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCommissionRulesRouteImport } from './routes/_authenticated/commission-rules'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEstatesRouteImport } from './routes/_authenticated/estates'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedRealtorsRouteImport } from './routes/_authenticated/realtors'
import { Route as AuthenticatedReceivablesRouteImport } from './routes/_authenticated/receivables'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedReserveRouteImport } from './routes/_authenticated/reserve'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts.index'
import { Route as AuthenticatedAccountsPaymentsRouteImport } from './routes/_authenticated/accounts.payments'
import { Route as AuthenticatedDocumentationIndexRouteImport } from './routes/_authenticated/documentation.index'
import { Route as AuthenticatedMyWorkIndexRouteImport } from './routes/_authenticated/my-work.index'
import { Route as AuthenticatedMyWorkInspectionsRouteImport } from './routes/_authenticated/my-work.inspections'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations.index'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties.$propertyId'
import { Route as AuthenticatedPropertiesSearchRouteImport } from './routes/_authenticated/properties.search'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedSalesSaleIdRouteImport } from './routes/_authenticated/sales.$saleId'
import { Route as AuthenticatedMyWorkLeadsIndexRouteImport } from './routes/_authenticated/my-work.leads.index'
import { Route as AuthenticatedMyWorkLeadsLeadIdRouteImport } from './routes/_authenticated/my-work.leads.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionRulesRoute =
  AuthenticatedCommissionRulesRouteImport.update({
    id: '/commission-rules',
    path: '/commission-rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstatesRoute = AuthenticatedEstatesRouteImport.update({
  id: '/estates',
  path: '/estates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRealtorsRoute = AuthenticatedRealtorsRouteImport.update({
  id: '/realtors',
  path: '/realtors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceivablesRoute =
  AuthenticatedReceivablesRouteImport.update({
    id: '/receivables',
    path: '/receivables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReserveRoute = AuthenticatedReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsPaymentsRoute =
  AuthenticatedAccountsPaymentsRouteImport.update({
    id: '/accounts/payments',
    path: '/accounts/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentationIndexRoute =
  AuthenticatedDocumentationIndexRouteImport.update({
    id: '/documentation/',
    path: '/documentation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyWorkIndexRoute =
  AuthenticatedMyWorkIndexRouteImport.update({
    id: '/my-work/',
    path: '/my-work/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyWorkInspectionsRoute =
  AuthenticatedMyWorkInspectionsRouteImport.update({
    id: '/my-work/inspections',
    path: '/my-work/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesSearchRoute =
  AuthenticatedPropertiesSearchRouteImport.update({
    id: '/properties/search',
    path: '/properties/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesSaleIdRoute =
  AuthenticatedSalesSaleIdRouteImport.update({
    id: '/sales/$saleId',
    path: '/sales/$saleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyWorkLeadsIndexRoute =
  AuthenticatedMyWorkLeadsIndexRouteImport.update({
    id: '/my-work/leads/',
    path: '/my-work/leads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyWorkLeadsLeadIdRoute =
  AuthenticatedMyWorkLeadsLeadIdRouteImport.update({
    id: '/my-work/leads/$leadId',
    path: '/my-work/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/commission-rules': typeof AuthenticatedCommissionRulesRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/estates': typeof AuthenticatedEstatesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/realtors': typeof AuthenticatedRealtorsRoute
  '/receivables': typeof AuthenticatedReceivablesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/reserve': typeof AuthenticatedReserveRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/accounts/payments': typeof AuthenticatedAccountsPaymentsRoute
  '/my-work/inspections': typeof AuthenticatedMyWorkInspectionsRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/search': typeof AuthenticatedPropertiesSearchRoute
  '/sales/$saleId': typeof AuthenticatedSalesSaleIdRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/documentation/': typeof AuthenticatedDocumentationIndexRoute
  '/my-work/': typeof AuthenticatedMyWorkIndexRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/my-work/leads/$leadId': typeof AuthenticatedMyWorkLeadsLeadIdRoute
  '/my-work/leads/': typeof AuthenticatedMyWorkLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/commission-rules': typeof AuthenticatedCommissionRulesRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/estates': typeof AuthenticatedEstatesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/realtors': typeof AuthenticatedRealtorsRoute
  '/receivables': typeof AuthenticatedReceivablesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/reserve': typeof AuthenticatedReserveRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/accounts/payments': typeof AuthenticatedAccountsPaymentsRoute
  '/my-work/inspections': typeof AuthenticatedMyWorkInspectionsRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/search': typeof AuthenticatedPropertiesSearchRoute
  '/sales/$saleId': typeof AuthenticatedSalesSaleIdRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/documentation': typeof AuthenticatedDocumentationIndexRoute
  '/my-work': typeof AuthenticatedMyWorkIndexRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/my-work/leads/$leadId': typeof AuthenticatedMyWorkLeadsLeadIdRoute
  '/my-work/leads': typeof AuthenticatedMyWorkLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/commission-rules': typeof AuthenticatedCommissionRulesRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/estates': typeof AuthenticatedEstatesRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/realtors': typeof AuthenticatedRealtorsRoute
  '/_authenticated/receivables': typeof AuthenticatedReceivablesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/reserve': typeof AuthenticatedReserveRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/accounts/payments': typeof AuthenticatedAccountsPaymentsRoute
  '/_authenticated/my-work/inspections': typeof AuthenticatedMyWorkInspectionsRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/_authenticated/properties/search': typeof AuthenticatedPropertiesSearchRoute
  '/_authenticated/sales/$saleId': typeof AuthenticatedSalesSaleIdRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/documentation/': typeof AuthenticatedDocumentationIndexRoute
  '/_authenticated/my-work/': typeof AuthenticatedMyWorkIndexRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/my-work/leads/$leadId': typeof AuthenticatedMyWorkLeadsLeadIdRoute
  '/_authenticated/my-work/leads/': typeof AuthenticatedMyWorkLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai'
    | '/audit'
    | '/commission-rules'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/estates'
    | '/expenses'
    | '/inspections'
    | '/inventory'
    | '/leads'
    | '/notifications'
    | '/payments'
    | '/portal'
    | '/projects'
    | '/realtors'
    | '/receivables'
    | '/reports'
    | '/reservations'
    | '/reserve'
    | '/settings'
    | '/tasks'
    | '/accounts/payments'
    | '/my-work/inspections'
    | '/properties/$propertyId'
    | '/properties/search'
    | '/sales/$saleId'
    | '/accounts/'
    | '/documentation/'
    | '/my-work/'
    | '/operations/'
    | '/sales/'
    | '/my-work/leads/$leadId'
    | '/my-work/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai'
    | '/audit'
    | '/commission-rules'
    | '/commissions'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/estates'
    | '/expenses'
    | '/inspections'
    | '/inventory'
    | '/leads'
    | '/notifications'
    | '/payments'
    | '/portal'
    | '/projects'
    | '/realtors'
    | '/receivables'
    | '/reports'
    | '/reservations'
    | '/reserve'
    | '/settings'
    | '/tasks'
    | '/accounts/payments'
    | '/my-work/inspections'
    | '/properties/$propertyId'
    | '/properties/search'
    | '/sales/$saleId'
    | '/accounts'
    | '/documentation'
    | '/my-work'
    | '/operations'
    | '/sales'
    | '/my-work/leads/$leadId'
    | '/my-work/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai'
    | '/_authenticated/audit'
    | '/_authenticated/commission-rules'
    | '/_authenticated/commissions'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/estates'
    | '/_authenticated/expenses'
    | '/_authenticated/inspections'
    | '/_authenticated/inventory'
    | '/_authenticated/leads'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/portal'
    | '/_authenticated/projects'
    | '/_authenticated/realtors'
    | '/_authenticated/receivables'
    | '/_authenticated/reports'
    | '/_authenticated/reservations'
    | '/_authenticated/reserve'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/accounts/payments'
    | '/_authenticated/my-work/inspections'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/properties/search'
    | '/_authenticated/sales/$saleId'
    | '/_authenticated/accounts/'
    | '/_authenticated/documentation/'
    | '/_authenticated/my-work/'
    | '/_authenticated/operations/'
    | '/_authenticated/sales/'
    | '/_authenticated/my-work/leads/$leadId'
    | '/_authenticated/my-work/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commission-rules': {
      id: '/_authenticated/commission-rules'
      path: '/commission-rules'
      fullPath: '/commission-rules'
      preLoaderRoute: typeof AuthenticatedCommissionRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estates': {
      id: '/_authenticated/estates'
      path: '/estates'
      fullPath: '/estates'
      preLoaderRoute: typeof AuthenticatedEstatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/realtors': {
      id: '/_authenticated/realtors'
      path: '/realtors'
      fullPath: '/realtors'
      preLoaderRoute: typeof AuthenticatedRealtorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receivables': {
      id: '/_authenticated/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof AuthenticatedReceivablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reserve': {
      id: '/_authenticated/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof AuthenticatedReserveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/payments': {
      id: '/_authenticated/accounts/payments'
      path: '/accounts/payments'
      fullPath: '/accounts/payments'
      preLoaderRoute: typeof AuthenticatedAccountsPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentation/': {
      id: '/_authenticated/documentation/'
      path: '/documentation'
      fullPath: '/documentation/'
      preLoaderRoute: typeof AuthenticatedDocumentationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-work/': {
      id: '/_authenticated/my-work/'
      path: '/my-work'
      fullPath: '/my-work/'
      preLoaderRoute: typeof AuthenticatedMyWorkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-work/inspections': {
      id: '/_authenticated/my-work/inspections'
      path: '/my-work/inspections'
      fullPath: '/my-work/inspections'
      preLoaderRoute: typeof AuthenticatedMyWorkInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/search': {
      id: '/_authenticated/properties/search'
      path: '/properties/search'
      fullPath: '/properties/search'
      preLoaderRoute: typeof AuthenticatedPropertiesSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/$saleId': {
      id: '/_authenticated/sales/$saleId'
      path: '/sales/$saleId'
      fullPath: '/sales/$saleId'
      preLoaderRoute: typeof AuthenticatedSalesSaleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-work/leads/': {
      id: '/_authenticated/my-work/leads/'
      path: '/my-work/leads'
      fullPath: '/my-work/leads/'
      preLoaderRoute: typeof AuthenticatedMyWorkLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-work/leads/$leadId': {
      id: '/_authenticated/my-work/leads/$leadId'
      path: '/my-work/leads/$leadId'
      fullPath: '/my-work/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedMyWorkLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCommissionRulesRoute: typeof AuthenticatedCommissionRulesRoute
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEstatesRoute: typeof AuthenticatedEstatesRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRealtorsRoute: typeof AuthenticatedRealtorsRoute
  AuthenticatedReceivablesRoute: typeof AuthenticatedReceivablesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedReserveRoute: typeof AuthenticatedReserveRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedAccountsPaymentsRoute: typeof AuthenticatedAccountsPaymentsRoute
  AuthenticatedMyWorkInspectionsRoute: typeof AuthenticatedMyWorkInspectionsRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRoute
  AuthenticatedPropertiesSearchRoute: typeof AuthenticatedPropertiesSearchRoute
  AuthenticatedSalesSaleIdRoute: typeof AuthenticatedSalesSaleIdRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedDocumentationIndexRoute: typeof AuthenticatedDocumentationIndexRoute
  AuthenticatedMyWorkIndexRoute: typeof AuthenticatedMyWorkIndexRoute
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
  AuthenticatedMyWorkLeadsLeadIdRoute: typeof AuthenticatedMyWorkLeadsLeadIdRoute
  AuthenticatedMyWorkLeadsIndexRoute: typeof AuthenticatedMyWorkLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCommissionRulesRoute: AuthenticatedCommissionRulesRoute,
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEstatesRoute: AuthenticatedEstatesRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRealtorsRoute: AuthenticatedRealtorsRoute,
  AuthenticatedReceivablesRoute: AuthenticatedReceivablesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedReserveRoute: AuthenticatedReserveRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedAccountsPaymentsRoute: AuthenticatedAccountsPaymentsRoute,
  AuthenticatedMyWorkInspectionsRoute: AuthenticatedMyWorkInspectionsRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRoute,
  AuthenticatedPropertiesSearchRoute: AuthenticatedPropertiesSearchRoute,
  AuthenticatedSalesSaleIdRoute: AuthenticatedSalesSaleIdRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedDocumentationIndexRoute: AuthenticatedDocumentationIndexRoute,
  AuthenticatedMyWorkIndexRoute: AuthenticatedMyWorkIndexRoute,
  AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  AuthenticatedMyWorkLeadsLeadIdRoute: AuthenticatedMyWorkLeadsLeadIdRoute,
  AuthenticatedMyWorkLeadsIndexRoute: AuthenticatedMyWorkLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
