CREATE TABLE IF NOT EXISTS public.company_profile (
    id bigint primary key generated by default as identity,
    legal_name text not null default 'NEOMARC REALTY',
    trading_name text,
    rc_number text,
    tin text,
    vat_number text,
    phone text,
    email text,
    website text,
    address text,
    currency text not null default 'NGN',
    fiscal_year_start_month int not null default 1,
    vat_rate numeric not null default 0,
    wht_rate numeric not null default 0,
    timezone text not null default 'Africa/Lagos',
    site_name text DEFAULT 'NEOMARC REALTY',
    site_abbreviation text DEFAULT 'N',
    site_description text DEFAULT 'NEOMARC Digital Operating System',
    logo_url text,
    favicon_url text,
    updated_at timestamp with time zone default now(),
    updated_by uuid references auth.users(id)
);

-- Insert default row
INSERT INTO public.company_profile (id, legal_name) VALUES (1, 'NEOMARC REALTY') ON CONFLICT DO NOTHING;

-- RLS
ALTER TABLE public.company_profile ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.company_profile FOR SELECT USING (true);
CREATE POLICY "Enable update for admins" ON public.company_profile FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role IN ('super_admin', 'management'))
);
CREATE POLICY "Enable insert for admins" ON public.company_profile FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role IN ('super_admin', 'management'))
);

NOTIFY pgrst, 'reload schema';

-- Add brand_assets storage bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('brand_assets', 'brand_assets', true) ON CONFLICT DO NOTHING;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'brand_assets');
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'brand_assets' AND auth.role() = 'authenticated');
CREATE POLICY "Auth Update" ON storage.objects FOR UPDATE USING (bucket_id = 'brand_assets' AND auth.role() = 'authenticated');
CREATE POLICY "Auth Delete" ON storage.objects FOR DELETE USING (bucket_id = 'brand_assets' AND auth.role() = 'authenticated');
